<a href="https://colab.research.google.com/github/Ashani-Sansala/Deep-Learning-Tensorflow/blob/main/Deep_Learning_for_Computer_Vision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import tensorflow as tf
import numpy as np

In [34]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [35]:
tensor_one_d = tf.constant([2,0,30,-1, 1.0], dtype=tf.float16)
print(tensor_one_d)

tf.Tensor([ 2.  0. 30. -1.  1.], shape=(5,), dtype=float16)


In [36]:
tensor_two_d = tf.constant([
    [1,2,0],
    [2,5,8],
    [-1,-9,10],
    [2,4,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 2  5  8]
 [-1 -9 10]
 [ 2  4  8]], shape=(4, 3), dtype=int32)


In [37]:
tensor_three_d = tf.constant([
    [[1,2,0], 
     [2,5,8],
     [-1,-9,10],
     [2,4,8]],

     [[1,-2,0], 
     [2,3,8],
     [-1,1,10],
     [10,3,8]],

     [[1,0,0], 
     [1,5,4],
     [-1,9,10],
     [0,4,8]]

])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 2  5  8]
  [-1 -9 10]
  [ 2  4  8]]

 [[ 1 -2  0]
  [ 2  3  8]
  [-1  1 10]
  [10  3  8]]

 [[ 1  0  0]
  [ 1  5  4]
  [-1  9 10]
  [ 0  4  8]]], shape=(3, 4, 3), dtype=int32)


In [38]:
tensor_four_d = tf.constant([
    [[[1,2,0], 
     [2,5,8],
     [-1,-9,10],
     [2,4,8]],

     [[1,-2,0], 
     [2,3,8],
     [-1,1,10],
     [10,3,8]],

     [[1,0,0], 
     [1,5,4],
     [-1,9,10],
     [0,4,8]]
    ],

    [[[1,2,0], 
     [2,5,8],
     [-1,-9,10],
     [2,4,8]],

     [[1,-2,0], 
     [2,3,8],
     [-1,1,10],
     [10,3,8]],

     [[1,0,0], 
     [1,5,4],
     [-1,9,10],
     [0,4,8]]
],

[[[1,2,0], 
     [2,5,8],
     [-1,-9,10],
     [2,4,8]],

     [[1,-2,0], 
     [2,3,8],
     [-1,1,10],
     [10,3,8]],

     [[1,0,0], 
     [1,5,4],
     [-1,9,10],
     [0,4,8]]
]
])

print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  0]
   [ 2  5  8]
   [-1 -9 10]
   [ 2  4  8]]

  [[ 1 -2  0]
   [ 2  3  8]
   [-1  1 10]
   [10  3  8]]

  [[ 1  0  0]
   [ 1  5  4]
   [-1  9 10]
   [ 0  4  8]]]


 [[[ 1  2  0]
   [ 2  5  8]
   [-1 -9 10]
   [ 2  4  8]]

  [[ 1 -2  0]
   [ 2  3  8]
   [-1  1 10]
   [10  3  8]]

  [[ 1  0  0]
   [ 1  5  4]
   [-1  9 10]
   [ 0  4  8]]]


 [[[ 1  2  0]
   [ 2  5  8]
   [-1 -9 10]
   [ 2  4  8]]

  [[ 1 -2  0]
   [ 2  3  8]
   [-1  1 10]
   [10  3  8]]

  [[ 1  0  0]
   [ 1  5  4]
   [-1  9 10]
   [ 0  4  8]]]], shape=(3, 3, 4, 3), dtype=int32)


In [39]:
tensor_bool = tf.constant([True, False, True, True])
print(tensor_bool)

tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


In [40]:
tensor_string = tf.constant(["Hello", "Hi", "Bye"])
print(tensor_string)

tf.Tensor([b'Hello' b'Hi' b'Bye'], shape=(3,), dtype=string)


In [41]:
np_array = np.array([2,6,10])
print(np_array)

[ 2  6 10]


In [42]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([ 2  6 10], shape=(3,), dtype=int64)


In [43]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor) #identity matrix

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [44]:
print(3*eye_tensor)

tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [45]:
eye_tensor1 = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor1)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float32)


In [46]:
fill_tensor = tf.fill(
    [1,3,4],5, name=None
)

print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [47]:
ones_tensor = tf.ones(
    [5,3],
    dtype=tf.dtypes.int32,
    name=None
)

print(ones_tensor)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]], shape=(5, 3), dtype=int32)


In [48]:
ones_like_tensor = tf.ones_like(fill_tensor)

print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


In [49]:
zeros_tensor = tf.zeros(
    shape = [2,3],
    dtype=tf.dtypes.float32,
    name=None
)

print(zeros_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [51]:
random_tensor = tf.random.normal(
    [3,2],
    mean=0.0, #Mean value of the normal distribution
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_tensor)

tf.Tensor(
[[ 0.13429876  1.2367196 ]
 [ 1.0392749  -0.3884726 ]
 [ 0.547374    1.0946507 ]], shape=(3, 2), dtype=float32)
