<a href="https://colab.research.google.com/github/Ashani-Sansala/Deep-Learning-Tensorflow/blob/main/Deep_Learning_for_Computer_Vision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([2,0,30,-1, 1.0], dtype=tf.float16)
print(tensor_one_d)

tf.Tensor([ 2.  0. 30. -1.  1.], shape=(5,), dtype=float16)


In [4]:
tensor_two_d = tf.constant([
    [1,2,0],
    [2,5,8],
    [-1,-9,10],
    [2,4,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 2  5  8]
 [-1 -9 10]
 [ 2  4  8]], shape=(4, 3), dtype=int32)


In [5]:
tensor_three_d = tf.constant([
    [[1,2,0], 
     [2,5,8],
     [-1,-9,10],
     [2,4,8]],

     [[1,-2,0], 
     [2,3,8],
     [-1,1,10],
     [10,3,8]],

     [[1,0,0], 
     [1,5,4],
     [-1,9,10],
     [0,4,8]]

])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 2  5  8]
  [-1 -9 10]
  [ 2  4  8]]

 [[ 1 -2  0]
  [ 2  3  8]
  [-1  1 10]
  [10  3  8]]

 [[ 1  0  0]
  [ 1  5  4]
  [-1  9 10]
  [ 0  4  8]]], shape=(3, 4, 3), dtype=int32)


In [6]:
tensor_four_d = tf.constant([
    [[[1,2,0], 
     [2,5,8],
     [-1,-9,10],
     [2,4,8]],

     [[1,-2,0], 
     [2,3,8],
     [-1,1,10],
     [10,3,8]],

     [[1,0,0], 
     [1,5,4],
     [-1,9,10],
     [0,4,8]]
    ],

    [[[1,2,0], 
     [2,5,8],
     [-1,-9,10],
     [2,4,8]],

     [[1,-2,0], 
     [2,3,8],
     [-1,1,10],
     [10,3,8]],

     [[1,0,0], 
     [1,5,4],
     [-1,9,10],
     [0,4,8]]
],

[[[1,2,0], 
     [2,5,8],
     [-1,-9,10],
     [2,4,8]],

     [[1,-2,0], 
     [2,3,8],
     [-1,1,10],
     [10,3,8]],

     [[1,0,0], 
     [1,5,4],
     [-1,9,10],
     [0,4,8]]
]
])

print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  0]
   [ 2  5  8]
   [-1 -9 10]
   [ 2  4  8]]

  [[ 1 -2  0]
   [ 2  3  8]
   [-1  1 10]
   [10  3  8]]

  [[ 1  0  0]
   [ 1  5  4]
   [-1  9 10]
   [ 0  4  8]]]


 [[[ 1  2  0]
   [ 2  5  8]
   [-1 -9 10]
   [ 2  4  8]]

  [[ 1 -2  0]
   [ 2  3  8]
   [-1  1 10]
   [10  3  8]]

  [[ 1  0  0]
   [ 1  5  4]
   [-1  9 10]
   [ 0  4  8]]]


 [[[ 1  2  0]
   [ 2  5  8]
   [-1 -9 10]
   [ 2  4  8]]

  [[ 1 -2  0]
   [ 2  3  8]
   [-1  1 10]
   [10  3  8]]

  [[ 1  0  0]
   [ 1  5  4]
   [-1  9 10]
   [ 0  4  8]]]], shape=(3, 3, 4, 3), dtype=int32)


In [7]:
tensor_bool = tf.constant([True, False, True, True])
print(tensor_bool)

tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


In [8]:
tensor_string = tf.constant(["Hello", "Hi", "Bye"])
print(tensor_string)

tf.Tensor([b'Hello' b'Hi' b'Bye'], shape=(3,), dtype=string)


In [9]:
np_array = np.array([2,6,10])
print(np_array)

[ 2  6 10]


In [10]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([ 2  6 10], shape=(3,), dtype=int64)


In [11]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor) #identity matrix

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [12]:
print(3*eye_tensor)

tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [13]:
eye_tensor1 = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor1)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float32)


In [14]:
fill_tensor = tf.fill(
    [1,3,4],5, name=None
)

print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [15]:
ones_tensor = tf.ones(
    [5,3],
    dtype=tf.dtypes.int32,
    name=None
)

print(ones_tensor)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]], shape=(5, 3), dtype=int32)


In [16]:
ones_like_tensor = tf.ones_like(fill_tensor)

print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


In [17]:
zeros_tensor = tf.zeros(
    shape = [2,3],
    dtype=tf.dtypes.float32,
    name=None
)

print(zeros_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [18]:
random_tensor = tf.random.normal(
    [3,2],
    mean=0.0, #Mean value of the normal distribution
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_tensor)

tf.Tensor(
[[ 9.0306037e-04  4.6425256e-01]
 [-2.4985459e-01  5.1196909e-01]
 [ 5.9566760e-01  1.5111424e+00]], shape=(3, 2), dtype=float32)


In [19]:
uniform_random_tensor = tf.random.uniform(
    [2,3],
    minval=0,
    maxval=100,
    dtype=tf.dtypes.float32,
    seed=5,
    name=None
)

print(uniform_random_tensor)

tf.Tensor(
[[38.831127 66.36828  19.191074]
 [70.60526  96.318344 32.628323]], shape=(2, 3), dtype=float32)


In [20]:
tensor_seed = tf.random.set_seed(
    10
)

print(tf.random.uniform([2,],maxval=100, dtype=tf.dtypes.float32,seed=5))
print(tf.random.uniform([2,],maxval=100, dtype=tf.dtypes.float32,seed=5))
print(tf.random.uniform([2,],maxval=100, dtype=tf.dtypes.float32,seed=5))
print(tf.random.uniform([2,],maxval=100, dtype=tf.dtypes.float32,seed=5))

tf.Tensor([98.94415  36.855625], shape=(2,), dtype=float32)
tf.Tensor([25.170158   3.6970735], shape=(2,), dtype=float32)
tf.Tensor([23.782969 68.802086], shape=(2,), dtype=float32)
tf.Tensor([94.44143  95.781235], shape=(2,), dtype=float32)


In [21]:
#########    Indexing  #############

In [22]:
tensor_indexd = tf.constant([1,10,-3,5,27])

print(tensor_indexd)
print(tensor_indexd[0])
print(tensor_indexd[1])

tf.Tensor([ 1 10 -3  5 27], shape=(5,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)


In [23]:
print(tensor_indexd[1:3])
print(tensor_indexd[1])

tf.Tensor([10 -3], shape=(2,), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)


In [24]:
tf.range(1,6)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [25]:
tensor_two_d = tf.constant([
    [1,2,0],
    [2,5,8],
    [-1,-9,10],
    [2,4,8]
])
# print(tensor_two_d[row range, column range])
print(tensor_two_d[0:3, 0:2])

tf.Tensor(
[[ 1  2]
 [ 2  5]
 [-1 -9]], shape=(3, 2), dtype=int32)


In [26]:
print(tensor_two_d[2, 1:])

tf.Tensor([-9 10], shape=(2,), dtype=int32)


In [27]:
print(tensor_two_d[:, 0])

tf.Tensor([ 1  2 -1  2], shape=(4,), dtype=int32)


In [28]:
tensor_three_d = tf.constant([
    [[1,2,0], 
     [2,5,8],
     [-1,-9,10],
     [2,4,8]],

     [[1,-2,0], 
     [2,3,8],
     [-1,1,10],
     [10,3,8]],

     [[1,0,0], 
     [1,5,4],
     [-1,9,10],
     [0,4,8]]

])
print(tensor_three_d[0:2, ..., 2])

tf.Tensor(
[[ 0  8 10  8]
 [ 0  8 10  8]], shape=(2, 4), dtype=int32)


In [29]:
print(tensor_three_d[..., :, 2])

tf.Tensor(
[[ 0  8 10  8]
 [ 0  8 10  8]
 [ 0  4 10  8]], shape=(3, 4), dtype=int32)


# Math Operations

In [30]:
abs_tensor = tf.math.abs(
    [-1,10,-3], name=None
)

print(abs_tensor)     # Absolute values

tf.Tensor([ 1 10  3], shape=(3,), dtype=int32)


In [31]:
complex_tensor = tf.math.abs([4+3j])

print(complex_tensor)

tf.Tensor([5.], shape=(1,), dtype=float64)


In [32]:
add_tensor = tf.math.add([2,3,4,5], [1,2,3,4])

print(add_tensor)

tf.Tensor([3 5 7 9], shape=(4,), dtype=int32)


In [33]:
multiply_tensor = tf.math.multiply([2,3,4,5], [1,2,3,4])

print(multiply_tensor)

tf.Tensor([ 2  6 12 20], shape=(4,), dtype=int32)


In [34]:
tf.sqrt(25.00)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [35]:
x = tf.constant([2,4,6,8])
y = tf.constant([7])

print(tf.math.add(x,y))
print(tf.math.multiply(x,y))

tf.Tensor([ 9 11 13 15], shape=(4,), dtype=int32)
tf.Tensor([14 28 42 56], shape=(4,), dtype=int32)


In [36]:
x = tf.constant([2,4,6,8,7,1])
y = tf.constant([[7], [5], [3]])

print(tf.math.multiply(x,y))

tf.Tensor(
[[14 28 42 56 49  7]
 [10 20 30 40 35  5]
 [ 6 12 18 24 21  3]], shape=(3, 6), dtype=int32)


In [37]:
max_tensor = tf.math.maximum(2,4)

print(max_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [38]:
min_tensor = tf.math.minimum(2,4)

print(min_tensor)

tf.Tensor(2, shape=(), dtype=int32)


In [39]:
arg_tensor = tf.math.argmax(
    [[14, 28, 42, 56, 49,  7], [140, 280, 42, 5060, 49,  7]],
    axis=0, # 0-column , 1-row
    output_type=tf.dtypes.int64,
    name=None
)

print(arg_tensor)

tf.Tensor([1 1 0 1 0 0], shape=(6,), dtype=int64)


In [40]:
arg_tensor = tf.math.argmax(
    [[14, 28, 42, 56, 49,  7], [140, 280, 42, 5060, 49,  7]],
    axis=1, # 0-column , 1-row
    output_type=tf.dtypes.int64,
    name=None
)

print(arg_tensor)

tf.Tensor([3 3], shape=(2,), dtype=int64)


In [41]:
equal_tensor = tf.math.equal(
    [2,3], [2,6], name=None
)

print(equal_tensor)

tf.Tensor([ True False], shape=(2,), dtype=bool)


In [42]:
pow_tensor = tf.math.pow(
    [2,3], [2,2], name=None
)

print(pow_tensor) # 2^2 , 3^2

tf.Tensor([4 9], shape=(2,), dtype=int32)


In [43]:
reduce_sum_tensor = tf.math.reduce_sum(
    [[14, 28, 42, 56, 49,  7], [140, 280, 42, 5060, 49,  7]],
    axis=None, 
    keepdims=False, 
    name=None
)

print(reduce_sum_tensor) # sum among all elements

tf.Tensor(5774, shape=(), dtype=int32)


In [44]:
reduce_max_tensor = tf.math.reduce_max(
    [[14, 28, 42, 56, 49,  7], [140, 280, 42, 5060, 49,  7]],
    axis=1, 
    keepdims=True, 
    name=None
)

print(reduce_max_tensor) # max among all elements

tf.Tensor(
[[  56]
 [5060]], shape=(2, 1), dtype=int32)


In [45]:
sigmoid_tensor = tf.math.sigmoid(
    [2.5,4.5,6.5,8.5,7.5,1.5], name=None  # data type should be floating point
)

print(sigmoid_tensor)

tf.Tensor([0.9241418  0.9890131  0.9984988  0.99979657 0.9994472  0.8175745 ], shape=(6,), dtype=float32)


In [46]:
top_k_tensor = tf.math.top_k(
    [2,3,4,5,10,6], 
    k=1,      # k - how many k elements we want
    sorted=True, 
    name=None
)

print(top_k_tensor)

TopKV2(values=<tf.Tensor: shape=(1,), dtype=int32, numpy=array([10], dtype=int32)>, indices=<tf.Tensor: shape=(1,), dtype=int32, numpy=array([4], dtype=int32)>)


# Linear Algebra Operations

In [47]:
a = tf.constant([[14, 28, 42]])
b = tf.constant([[1],[2],[3]])

matrics_mul_tensor = tf.linalg.matmul(
    a,
    b,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)

print(matrics_mul_tensor)

tf.Tensor([[196]], shape=(1, 1), dtype=int32)


In [48]:
a@b

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[196]], dtype=int32)>

In [49]:
transpose_tensor = tf.linalg.matrix_transpose(
    a, name='matrix_transpose', conjugate=False
)

print(transpose_tensor)

tf.Tensor(
[[14]
 [28]
 [42]], shape=(3, 1), dtype=int32)


In [50]:
print(tf.transpose(b))

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [51]:
a = tf.constant([[14, 28],[2, 5]])
b = tf.constant([[1, 0, 5],[2, 2,6]])

matrics_mul_2d_tensor = tf.linalg.matmul(
    a,
    b
)

print(matrics_mul_2d_tensor)  # 2D matrix multiplication 

tf.Tensor(
[[ 70  56 238]
 [ 12  10  40]], shape=(2, 3), dtype=int32)


In [52]:
t = tf.constant([[ 0,  1,  2, 3],                
                [-1,  0,  1, 2],
                [-2, -1,  0, 1],
                [-3, -2, -1, 0]])
 
 
upper_t = tf.linalg.band_part(t, 0, -1) # Upper triangular part.
lower_t = tf.linalg.band_part(t, -1, 0) # Lower triangular part.
diagonal_t = tf.linalg.band_part(t, 0, 0) # Diagonal

print(upper_t)
print(lower_t)
print(diagonal_t)

tf.Tensor(
[[0 1 2 3]
 [0 0 1 2]
 [0 0 0 1]
 [0 0 0 0]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[ 0  0  0  0]
 [-1  0  0  0]
 [-2 -1  0  0]
 [-3 -2 -1  0]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(4, 4), dtype=int32)


In [53]:
upper_t = tf.linalg.band_part(t, -1, -1) 
lower_t = tf.linalg.band_part(t, 2, -1) 
diagonal_t = tf.linalg.band_part(t, 0, 0)

print(upper_t)
print(lower_t)
print(diagonal_t)

tf.Tensor(
[[ 0  1  2  3]
 [-1  0  1  2]
 [-2 -1  0  1]
 [-3 -2 -1  0]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[ 0  1  2  3]
 [-1  0  1  2]
 [-2 -1  0  1]
 [ 0 -2 -1  0]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(4, 4), dtype=int32)


In [54]:
a = tf.constant([[14, 28,4],[2, 5,5]])
b = tf.constant([[1, 0, 3],[2,6, 2]])

cross_pro_tensor = tf.linalg.cross(
    a, b, name=None
)

print(cross_pro_tensor)

tf.Tensor(
[[ 84 -38 -28]
 [-20   6   2]], shape=(2, 3), dtype=int32)


In [55]:
a = tf.constant([[14, 28,4],[2, 5,5], [1, 2, 3]], dtype = tf.float32)  # data type should be floating point

inverse_tensor = tf.linalg.inv(
    a, adjoint=False, name=None
)

print(inverse_tensor) 

tf.Tensor(
[[ 0.13157895 -2.          3.1578948 ]
 [-0.02631579  1.         -1.631579  ]
 [-0.02631579  0.          0.36842108]], shape=(3, 3), dtype=float32)


In [56]:
inverse_tensor@a  # unit matrix

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.0000002e+00,  4.7683716e-07,  2.3841858e-07],
       [-1.1920929e-07,  9.9999976e-01, -3.5762787e-07],
       [ 0.0000000e+00,  0.0000000e+00,  1.0000001e+00]], dtype=float32)>

#Einsum Operator

In [60]:
A = np.array([[1,2], [2,3], [4,7]])

B = np.array([[1,2,5], [2,3,0]])

C = np.array([[1,5], [0,3], [4,2]])

print(np.matmul(A,B),"\n")

print(np.einsum("ij,jk -> ik", A,B))  # matrix multiplication

[[ 5  8  5]
 [ 8 13 10]
 [18 29 20]] 

[[ 5  8  5]
 [ 8 13 10]
 [18 29 20]]


In [63]:
print(A*C, "\n")

print(np.einsum("ij, ij -> ij", A,C))  # Elementwise multiplication

[[ 1 10]
 [ 0  9]
 [16 14]] 

[[ 1 10]
 [ 0  9]
 [16 14]]


In [65]:
print(A.T, "\n")

print(np.einsum("ij -> ji", A))  # Transpose

[[1 2 4]
 [2 3 7]] 

[[1 2 4]
 [2 3 7]]
