<a href="https://colab.research.google.com/github/Ashani-Sansala/Deep-Learning-Tensorflow/blob/main/Deep_Learning_for_Computer_Vision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([2,0,30,-1, 1.0], dtype=tf.float16)
print(tensor_one_d)

tf.Tensor([ 2.  0. 30. -1.  1.], shape=(5,), dtype=float16)


In [4]:
tensor_two_d = tf.constant([
    [1,2,0],
    [2,5,8],
    [-1,-9,10],
    [2,4,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 2  5  8]
 [-1 -9 10]
 [ 2  4  8]], shape=(4, 3), dtype=int32)


In [5]:
tensor_three_d = tf.constant([
    [[1,2,0],
     [2,5,8],
     [-1,-9,10],
     [2,4,8]],

     [[1,-2,0],
     [2,3,8],
     [-1,1,10],
     [10,3,8]],

     [[1,0,0],
     [1,5,4],
     [-1,9,10],
     [0,4,8]]

])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 2  5  8]
  [-1 -9 10]
  [ 2  4  8]]

 [[ 1 -2  0]
  [ 2  3  8]
  [-1  1 10]
  [10  3  8]]

 [[ 1  0  0]
  [ 1  5  4]
  [-1  9 10]
  [ 0  4  8]]], shape=(3, 4, 3), dtype=int32)


In [6]:
tensor_four_d = tf.constant([
    [[[1,2,0],
     [2,5,8],
     [-1,-9,10],
     [2,4,8]],

     [[1,-2,0],
     [2,3,8],
     [-1,1,10],
     [10,3,8]],

     [[1,0,0],
     [1,5,4],
     [-1,9,10],
     [0,4,8]]
    ],

    [[[1,2,0],
     [2,5,8],
     [-1,-9,10],
     [2,4,8]],

     [[1,-2,0],
     [2,3,8],
     [-1,1,10],
     [10,3,8]],

     [[1,0,0],
     [1,5,4],
     [-1,9,10],
     [0,4,8]]
],

[[[1,2,0],
     [2,5,8],
     [-1,-9,10],
     [2,4,8]],

     [[1,-2,0],
     [2,3,8],
     [-1,1,10],
     [10,3,8]],

     [[1,0,0],
     [1,5,4],
     [-1,9,10],
     [0,4,8]]
]
])

print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  0]
   [ 2  5  8]
   [-1 -9 10]
   [ 2  4  8]]

  [[ 1 -2  0]
   [ 2  3  8]
   [-1  1 10]
   [10  3  8]]

  [[ 1  0  0]
   [ 1  5  4]
   [-1  9 10]
   [ 0  4  8]]]


 [[[ 1  2  0]
   [ 2  5  8]
   [-1 -9 10]
   [ 2  4  8]]

  [[ 1 -2  0]
   [ 2  3  8]
   [-1  1 10]
   [10  3  8]]

  [[ 1  0  0]
   [ 1  5  4]
   [-1  9 10]
   [ 0  4  8]]]


 [[[ 1  2  0]
   [ 2  5  8]
   [-1 -9 10]
   [ 2  4  8]]

  [[ 1 -2  0]
   [ 2  3  8]
   [-1  1 10]
   [10  3  8]]

  [[ 1  0  0]
   [ 1  5  4]
   [-1  9 10]
   [ 0  4  8]]]], shape=(3, 3, 4, 3), dtype=int32)


In [7]:
tensor_bool = tf.constant([True, False, True, True])
print(tensor_bool)

tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


In [8]:
tensor_string = tf.constant(["Hello", "Hi", "Bye"])
print(tensor_string)

tf.Tensor([b'Hello' b'Hi' b'Bye'], shape=(3,), dtype=string)


In [9]:
np_array = np.array([2,6,10])
print(np_array)

[ 2  6 10]


In [10]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([ 2  6 10], shape=(3,), dtype=int64)


In [11]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor) #identity matrix

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [12]:
print(3*eye_tensor)

tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [13]:
eye_tensor1 = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor1)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float32)


In [14]:
fill_tensor = tf.fill(
    [1,3,4],5, name=None
)

print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [15]:
ones_tensor = tf.ones(
    [5,3],
    dtype=tf.dtypes.int32,
    name=None
)

print(ones_tensor)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]], shape=(5, 3), dtype=int32)


In [16]:
ones_like_tensor = tf.ones_like(fill_tensor)

print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


In [17]:
zeros_tensor = tf.zeros(
    shape = [2,3],
    dtype=tf.dtypes.float32,
    name=None
)

print(zeros_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [18]:
random_tensor = tf.random.normal(
    [3,2],
    mean=0.0, #Mean value of the normal distribution
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_tensor)

tf.Tensor(
[[ 0.51073676 -1.2124783 ]
 [-0.2500364   0.6619475 ]
 [ 1.468066    0.17463201]], shape=(3, 2), dtype=float32)


In [19]:
uniform_random_tensor = tf.random.uniform(
    [2,3],
    minval=0,
    maxval=100,
    dtype=tf.dtypes.float32,
    seed=5,
    name=None
)

print(uniform_random_tensor)

tf.Tensor(
[[38.831127 66.36828  19.191074]
 [70.60526  96.318344 32.628323]], shape=(2, 3), dtype=float32)


In [20]:
tensor_seed = tf.random.set_seed(
    10
)

print(tf.random.uniform([2,],maxval=100, dtype=tf.dtypes.float32,seed=5))
print(tf.random.uniform([2,],maxval=100, dtype=tf.dtypes.float32,seed=5))
print(tf.random.uniform([2,],maxval=100, dtype=tf.dtypes.float32,seed=5))
print(tf.random.uniform([2,],maxval=100, dtype=tf.dtypes.float32,seed=5))

tf.Tensor([98.94415  36.855625], shape=(2,), dtype=float32)
tf.Tensor([25.170158   3.6970735], shape=(2,), dtype=float32)
tf.Tensor([23.782969 68.802086], shape=(2,), dtype=float32)
tf.Tensor([94.44143  95.781235], shape=(2,), dtype=float32)


In [21]:
#########    Indexing  #############

In [22]:
tensor_indexd = tf.constant([1,10,-3,5,27])

print(tensor_indexd)
print(tensor_indexd[0])
print(tensor_indexd[1])

tf.Tensor([ 1 10 -3  5 27], shape=(5,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)


In [23]:
print(tensor_indexd[1:3])
print(tensor_indexd[1])

tf.Tensor([10 -3], shape=(2,), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)


In [24]:
tf.range(1,6)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [25]:
tensor_two_d = tf.constant([
    [1,2,0],
    [2,5,8],
    [-1,-9,10],
    [2,4,8]
])
# print(tensor_two_d[row range, column range])
print(tensor_two_d[0:3, 0:2])

tf.Tensor(
[[ 1  2]
 [ 2  5]
 [-1 -9]], shape=(3, 2), dtype=int32)


In [26]:
print(tensor_two_d[2, 1:])

tf.Tensor([-9 10], shape=(2,), dtype=int32)


In [27]:
print(tensor_two_d[:, 0])

tf.Tensor([ 1  2 -1  2], shape=(4,), dtype=int32)


In [28]:
tensor_three_d = tf.constant([
    [[1,2,0],
     [2,5,8],
     [-1,-9,10],
     [2,4,8]],

     [[1,-2,0],
     [2,3,8],
     [-1,1,10],
     [10,3,8]],

     [[1,0,0],
     [1,5,4],
     [-1,9,10],
     [0,4,8]]

])
print(tensor_three_d[0:2, ..., 2])

tf.Tensor(
[[ 0  8 10  8]
 [ 0  8 10  8]], shape=(2, 4), dtype=int32)


In [29]:
print(tensor_three_d[..., :, 2])

tf.Tensor(
[[ 0  8 10  8]
 [ 0  8 10  8]
 [ 0  4 10  8]], shape=(3, 4), dtype=int32)


# Math Operations

In [30]:
abs_tensor = tf.math.abs(
    [-1,10,-3], name=None
)

print(abs_tensor)     # Absolute values

tf.Tensor([ 1 10  3], shape=(3,), dtype=int32)


In [31]:
complex_tensor = tf.math.abs([4+3j])

print(complex_tensor)

tf.Tensor([5.], shape=(1,), dtype=float64)


In [32]:
add_tensor = tf.math.add([2,3,4,5], [1,2,3,4])

print(add_tensor)

tf.Tensor([3 5 7 9], shape=(4,), dtype=int32)


In [33]:
multiply_tensor = tf.math.multiply([2,3,4,5], [1,2,3,4])

print(multiply_tensor)

tf.Tensor([ 2  6 12 20], shape=(4,), dtype=int32)


In [34]:
tf.sqrt(25.00)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [35]:
x = tf.constant([2,4,6,8])
y = tf.constant([7])

print(tf.math.add(x,y))
print(tf.math.multiply(x,y))

tf.Tensor([ 9 11 13 15], shape=(4,), dtype=int32)
tf.Tensor([14 28 42 56], shape=(4,), dtype=int32)


In [36]:
x = tf.constant([2,4,6,8,7,1])
y = tf.constant([[7], [5], [3]])

print(tf.math.multiply(x,y))

tf.Tensor(
[[14 28 42 56 49  7]
 [10 20 30 40 35  5]
 [ 6 12 18 24 21  3]], shape=(3, 6), dtype=int32)


In [37]:
max_tensor = tf.math.maximum(2,4)

print(max_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [38]:
min_tensor = tf.math.minimum(2,4)

print(min_tensor)

tf.Tensor(2, shape=(), dtype=int32)


In [39]:
arg_tensor = tf.math.argmax(
    [[14, 28, 42, 56, 49,  7], [140, 280, 42, 5060, 49,  7]],
    axis=0, # 0-column , 1-row
    output_type=tf.dtypes.int64,
    name=None
)

print(arg_tensor)

tf.Tensor([1 1 0 1 0 0], shape=(6,), dtype=int64)


In [40]:
arg_tensor = tf.math.argmax(
    [[14, 28, 42, 56, 49,  7], [140, 280, 42, 5060, 49,  7]],
    axis=1, # 0-column , 1-row
    output_type=tf.dtypes.int64,
    name=None
)

print(arg_tensor)

tf.Tensor([3 3], shape=(2,), dtype=int64)


In [41]:
equal_tensor = tf.math.equal(
    [2,3], [2,6], name=None
)

print(equal_tensor)

tf.Tensor([ True False], shape=(2,), dtype=bool)


In [42]:
pow_tensor = tf.math.pow(
    [2,3], [2,2], name=None
)

print(pow_tensor) # 2^2 , 3^2

tf.Tensor([4 9], shape=(2,), dtype=int32)


In [43]:
reduce_sum_tensor = tf.math.reduce_sum(
    [[14, 28, 42, 56, 49,  7], [140, 280, 42, 5060, 49,  7]],
    axis=None,
    keepdims=False,
    name=None
)

print(reduce_sum_tensor) # sum among all elements

tf.Tensor(5774, shape=(), dtype=int32)


In [44]:
reduce_max_tensor = tf.math.reduce_max(
    [[14, 28, 42, 56, 49,  7], [140, 280, 42, 5060, 49,  7]],
    axis=1,
    keepdims=True,
    name=None
)

print(reduce_max_tensor) # max among all elements

tf.Tensor(
[[  56]
 [5060]], shape=(2, 1), dtype=int32)


In [45]:
sigmoid_tensor = tf.math.sigmoid(
    [2.5,4.5,6.5,8.5,7.5,1.5], name=None  # data type should be floating point
)

print(sigmoid_tensor)

tf.Tensor([0.9241418  0.9890131  0.9984988  0.99979657 0.9994472  0.8175745 ], shape=(6,), dtype=float32)


In [46]:
top_k_tensor = tf.math.top_k(
    [2,3,4,5,10,6],
    k=1,      # k - how many k elements we want
    sorted=True,
    name=None
)

print(top_k_tensor)

TopKV2(values=<tf.Tensor: shape=(1,), dtype=int32, numpy=array([10], dtype=int32)>, indices=<tf.Tensor: shape=(1,), dtype=int32, numpy=array([4], dtype=int32)>)


# Linear Algebra Operations

In [47]:
a = tf.constant([[14, 28, 42]])
b = tf.constant([[1],[2],[3]])

matrics_mul_tensor = tf.linalg.matmul(
    a,
    b,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)

print(matrics_mul_tensor)

tf.Tensor([[196]], shape=(1, 1), dtype=int32)


In [48]:
a@b

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[196]], dtype=int32)>

In [49]:
transpose_tensor = tf.linalg.matrix_transpose(
    a, name='matrix_transpose', conjugate=False
)

print(transpose_tensor)

tf.Tensor(
[[14]
 [28]
 [42]], shape=(3, 1), dtype=int32)


In [50]:
print(tf.transpose(b))

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [51]:
a = tf.constant([[14, 28],[2, 5]])
b = tf.constant([[1, 0, 5],[2, 2,6]])

matrics_mul_2d_tensor = tf.linalg.matmul(
    a,
    b
)

print(matrics_mul_2d_tensor)  # 2D matrix multiplication

tf.Tensor(
[[ 70  56 238]
 [ 12  10  40]], shape=(2, 3), dtype=int32)


In [52]:
t = tf.constant([[ 0,  1,  2, 3],
                [-1,  0,  1, 2],
                [-2, -1,  0, 1],
                [-3, -2, -1, 0]])


upper_t = tf.linalg.band_part(t, 0, -1) # Upper triangular part.
lower_t = tf.linalg.band_part(t, -1, 0) # Lower triangular part.
diagonal_t = tf.linalg.band_part(t, 0, 0) # Diagonal

print(upper_t)
print(lower_t)
print(diagonal_t)

tf.Tensor(
[[0 1 2 3]
 [0 0 1 2]
 [0 0 0 1]
 [0 0 0 0]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[ 0  0  0  0]
 [-1  0  0  0]
 [-2 -1  0  0]
 [-3 -2 -1  0]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(4, 4), dtype=int32)


In [53]:
upper_t = tf.linalg.band_part(t, -1, -1)
lower_t = tf.linalg.band_part(t, 2, -1)
diagonal_t = tf.linalg.band_part(t, 0, 0)

print(upper_t)
print(lower_t)
print(diagonal_t)

tf.Tensor(
[[ 0  1  2  3]
 [-1  0  1  2]
 [-2 -1  0  1]
 [-3 -2 -1  0]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[ 0  1  2  3]
 [-1  0  1  2]
 [-2 -1  0  1]
 [ 0 -2 -1  0]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(4, 4), dtype=int32)


In [54]:
a = tf.constant([[14, 28,4],[2, 5,5]])
b = tf.constant([[1, 0, 3],[2,6, 2]])

cross_pro_tensor = tf.linalg.cross(
    a, b, name=None
)

print(cross_pro_tensor)

tf.Tensor(
[[ 84 -38 -28]
 [-20   6   2]], shape=(2, 3), dtype=int32)


In [55]:
a = tf.constant([[14, 28,4],[2, 5,5], [1, 2, 3]], dtype = tf.float32)  # data type should be floating point

inverse_tensor = tf.linalg.inv(
    a, adjoint=False, name=None
)

print(inverse_tensor)

tf.Tensor(
[[ 0.13157895 -2.          3.1578948 ]
 [-0.02631579  1.         -1.631579  ]
 [-0.02631579  0.          0.36842108]], shape=(3, 3), dtype=float32)


In [56]:
inverse_tensor@a  # unit matrix

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.0000002e+00,  4.7683716e-07,  2.3841858e-07],
       [-1.1920929e-07,  9.9999976e-01, -3.5762787e-07],
       [ 0.0000000e+00,  0.0000000e+00,  1.0000001e+00]], dtype=float32)>

#Einsum Operator

In [57]:
A = np.array([[1,2], [2,3], [4,7]])

B = np.array([[1,2,5], [2,3,0]])

C = np.array([[1,5], [0,3], [4,2]])

print(np.matmul(A,B),"\n")

print(np.einsum("ij,jk -> ik", A,B))  # matrix multiplication

[[ 5  8  5]
 [ 8 13 10]
 [18 29 20]] 

[[ 5  8  5]
 [ 8 13 10]
 [18 29 20]]


In [58]:
print(A*C, "\n")

print(np.einsum("ij, ij -> ij", A,C))  # Elementwise multiplication

[[ 1 10]
 [ 0  9]
 [16 14]] 

[[ 1 10]
 [ 0  9]
 [16 14]]


In [59]:
print(A.T, "\n")

print(np.einsum("ij -> ji", A))  # Transpose

[[1 2 4]
 [2 3 7]] 

[[1 2 4]
 [2 3 7]]


In [60]:
A = np.array([[[1,2], [2,3], [4,7]], [[1,2], [2,3], [4,7]]])

B = np.array([[[1,5,3], [2,6,1]], [[2,2,5], [0,3,0]]])

print(A.shape, B.shape)

print(np.matmul(A,B), "\n")

print(np.einsum("bij, bjk -> bik", A,B))  # 3D matrix multiplication


(2, 3, 2) (2, 2, 3)
[[[ 5 17  5]
  [ 8 28  9]
  [18 62 19]]

 [[ 2  8  5]
  [ 4 13 10]
  [ 8 29 20]]] 

[[[ 5 17  5]
  [ 8 28  9]
  [18 62 19]]

 [[ 2  8  5]
  [ 4 13 10]
  [ 8 29 20]]]


In [61]:
print(np.sum(A), "\n")

print(np.einsum("bij -> ", A)) # sum of all elements

38 

38


In [62]:
print("ij -> j", A) # sum of columns

ij -> j [[[1 2]
  [2 3]
  [4 7]]

 [[1 2]
  [2 3]
  [4 7]]]


In [63]:
print("ij -> i", A) # sum of rows

ij -> i [[[1 2]
  [2 3]
  [4 7]]

 [[1 2]
  [2 3]
  [4 7]]]


# Tensorflow Functions

In [64]:
A = np.array([[[1,2], [2,3], [4,7]], [[1,2], [2,3], [4,7]]])

extra_dim = tf.expand_dims(
    A, axis = 3, name=None
)

print(extra_dim.shape)  # Add dimension of a

(2, 3, 2, 1)


In [65]:
squeezed_tensor = tf.squeeze(extra_dim, axis = 3)

print(A.shape) # removes dimension with length 1

(2, 3, 2)


In [66]:
a = tf.constant([[14, 28,4],[2, 5,5]])
print(a.shape)

b = tf.reshape(a, [6])

print(b.shape)

print(b)

(2, 3)
(6,)
tf.Tensor([14 28  4  2  5  5], shape=(6,), dtype=int32)


In [67]:
print(tf.reshape(a, [3,2]))

tf.Tensor(
[[14 28]
 [ 4  2]
 [ 5  5]], shape=(3, 2), dtype=int32)


In [68]:
print(tf.reshape(a, [3,-1]))  # Tensorflow automatically detects the shape as 3,2

tf.Tensor(
[[14 28]
 [ 4  2]
 [ 5  5]], shape=(3, 2), dtype=int32)


In [69]:
t1 = tf.constant([[14, 28, 4, 9],[2, 5, 5, 2]])

t2 = tf.constant([[34, 10, 3, 8],[1, -1, 0, 2]])

print(t1.shape)

print(t2.shape)

tf.concat([t1, t2], axis = 0)  # concat across columns

(2, 4)
(2, 4)


<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[14, 28,  4,  9],
       [ 2,  5,  5,  2],
       [34, 10,  3,  8],
       [ 1, -1,  0,  2]], dtype=int32)>

In [70]:
tf.concat([t1, t2], axis = 1)  # concat across rows

<tf.Tensor: shape=(2, 8), dtype=int32, numpy=
array([[14, 28,  4,  9, 34, 10,  3,  8],
       [ 2,  5,  5,  2,  1, -1,  0,  2]], dtype=int32)>

In [71]:
tf.stack([t1,t2], axis=0)

<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
array([[[14, 28,  4,  9],
        [ 2,  5,  5,  2]],

       [[34, 10,  3,  8],
        [ 1, -1,  0,  2]]], dtype=int32)>

In [72]:
tf.stack([t1,t2,t1], axis=0)

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[14, 28,  4,  9],
        [ 2,  5,  5,  2]],

       [[34, 10,  3,  8],
        [ 1, -1,  0,  2]],

       [[14, 28,  4,  9],
        [ 2,  5,  5,  2]]], dtype=int32)>

In [73]:
tf.stack([t1,t2,t1], axis=1)

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[14, 28,  4,  9],
        [34, 10,  3,  8],
        [14, 28,  4,  9]],

       [[ 2,  5,  5,  2],
        [ 1, -1,  0,  2],
        [ 2,  5,  5,  2]]], dtype=int32)>

In [74]:
tf.stack([t1,t2,t1], axis=2)

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[14, 34, 14],
        [28, 10, 28],
        [ 4,  3,  4],
        [ 9,  8,  9]],

       [[ 2,  1,  2],
        [ 5, -1,  5],
        [ 5,  0,  5],
        [ 2,  2,  2]]], dtype=int32)>

In [75]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
paddings = tf.constant([[1, 1,], [2, 2]])
# 'constant_values' is 0.
# rank of 't' is 2.
tf.pad(t, paddings, "CONSTANT")

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [76]:
tf.pad(t, paddings, "CONSTANT", constant_values = 3)

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 1, 2, 3, 3, 3],
       [3, 3, 4, 5, 6, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]], dtype=int32)>

In [77]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])

params[1:3+1]

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [78]:
tf.gather(params, [1,2,3])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [79]:
tf.gather(params, [0,5,3])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p0', b'p5', b'p3'], dtype=object)>

In [80]:
tf.gather(params, [0,5,3], axis = 0)

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p0', b'p5', b'p3'], dtype=object)>

In [81]:
indices = [
            [[1,0], [0,1]],

            [[0,0], [1,1]]
          ]

params = [
            [['a0','b0'], ['c0','d0']],

            [['a1','b1'], ['c1','d1']]
          ]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2, 2), dtype=string, numpy=
array([[[b'a1', b'b1'],
        [b'c0', b'd0']],

       [[b'a0', b'b0'],
        [b'c1', b'd1']]], dtype=object)>

In [82]:
tf.gather_nd(params, indices, batch_dims = 1)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'c0', b'b0'],
       [b'a1', b'd1']], dtype=object)>

# Ragged Tensors

In [83]:
tensor_two_d = [[[1,2],
                [2,],
                 [4,7]],

                [[1,2],
                 [2,3],
                  [4,]]]

tensor_ragged = tf.ragged.constant(tensor_two_d)
tensor_ragged.shape

TensorShape([2, None, None])

In [84]:
# 2-D example
tensor = [[1, 2], [3, 4], [5, 6]]
mask = np.array([True, False, True])
tf.boolean_mask(tensor, mask)  # [[1, 2], [5, 6]]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6]], dtype=int32)>

In [85]:
tensor_sparse = tf.sparse.SparseTensor(
    [[1,1], [3,4]], values = [11,56], dense_shape = [5,6]
)

print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [86]:
tf.sparse.to_dense(tensor_sparse)  # sparse tensor to a normal tensor

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

In [87]:
tensor_string = tf.constant(["Hi", "I am", "a string"])

print(tensor_string)

tf.Tensor([b'Hi' b'I am' b'a string'], shape=(3,), dtype=string)


In [88]:
tf.strings.join(
    tensor_string, separator=' ', name=None
)

<tf.Tensor: shape=(), dtype=string, numpy=b'Hi I am a string'>

In [89]:
tf.strings.join(
    tensor_string, separator=' + ', name=None
)

<tf.Tensor: shape=(), dtype=string, numpy=b'Hi + I am + a string'>

# Variables

In [90]:
x_var = tf.Variable(x, name = 'var1')

print(x_var)

<tf.Variable 'var1:0' shape=(6,) dtype=int32, numpy=array([2, 4, 6, 8, 7, 1], dtype=int32)>


In [97]:
x_var.assign_add([1,6,7,8,0,1])

<tf.Variable 'UnreadVariable' shape=(6,) dtype=int32, numpy=array([ 3, 10, 13, 16,  7,  2], dtype=int32)>

In [98]:
with tf.device('GPU:0'):
  x_var = tf.Variable(0.2)
  x_tensor = tf.constant(0.2)

  print(x_var.device)
  print(x_tensor.device)

/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0
